[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@rmrk-team/evm-contracts/contracts/=../node_modules/@rmrk-team/evm-contracts/contracts/", "@openzeppelin/=../node_modules/@openzeppelin/"]
allow_paths = ["../node_modules/@rmrk-team/evm-contracts/contracts/", "../node_modules/@openzeppelin/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
